services:
  backend:
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2

  celery_worker:
    command: celery -A app.worker.celery_app:celery_app worker --loglevel=info --concurrency=2